<template>
    <div class="spinner">
        <div class="loadingio-spinner-rolling-rbncn5fpql9"><div class="ldio-3q6i71flm1h">
            <div></div>
            </div></div>
    </div>
</template>

<script>
export default {
    name: 'Spinner'
}
</script>

<style>
@keyframes ldio-3q6i71flm1h {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.spinner {
    position: absolute;
    left: 45%;
    top: 45%;
}

.ldio-3q6i71flm1h div {
  position: absolute;
  width: 46.02px;
  height: 46.02px;
  border: 24.78px solid #c9acf2;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-3q6i71flm1h div {
  animation: ldio-3q6i71flm1h 1.0989010989010988s linear infinite;
  top: 88.5px;
  left: 88.5px
}
.loadingio-spinner-rolling-rbncn5fpql9 {
  width: 177px;
  height: 177px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-3q6i71flm1h {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-3q6i71flm1h div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>